<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://www.SettledTrx.org"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/SettledTrxBusinessService"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Resources/SettledTrxBusinessService.xsd"/>
        <oracle-xsl-mapper:rootElement name="SettledTrxBusinessServiceOutputCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SettledTrxBusinessService"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schema/SD_SettledTrx.xsd"/>
        <oracle-xsl-mapper:rootElement name="Settled_Transactions_OutputCollection"
                                       namespace="http://www.SettledTrx.org"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI JUN 05 10:53:35 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:Settled_Transactions_OutputCollection>
      <xsl:for-each select="/ns0:SettledTrxBusinessServiceOutputCollection/ns0:SettledTrxBusinessServiceOutput">
        <tns:settled_Transactions_Output>
          <tns:transactionDate>
            <xsl:value-of select="ns0:transactionDate"/>
          </tns:transactionDate>
          <tns:suborderTxnId>
            <xsl:value-of select="ns0:suborderTxnId"/>
          </tns:suborderTxnId>
          <tns:transactionType>
            <xsl:value-of select="ns0:transactionType"/>
          </tns:transactionType>
          <tns:transactionReason>
            <xsl:value-of select="ns0:transactionReason"/>
          </tns:transactionReason>
          <tns:sellerCode>
            <xsl:value-of select="ns0:sellerCode"/>
          </tns:sellerCode>
          <tns:productName>
            <xsl:value-of select="ns0:productName"/>
          </tns:productName>
          <tns:sellerSku>
            <xsl:value-of select="ns0:sellerSku"/>
          </tns:sellerSku>
          <tns:webSalePrice>
            <xsl:value-of select="string (ns0:webSalePrice )"/>
          </tns:webSalePrice>
          <tns:paidAmount>
            <xsl:value-of select="string (ns0:paidAmount )"/>
          </tns:paidAmount>
          <tns:knockedOff>
            <xsl:value-of select="ns0:knockedOff"/>
          </tns:knockedOff>
          <tns:paymentDate>
            <xsl:value-of select="ns0:paymentDate"/>
          </tns:paymentDate>
          <tns:erpSystemId>
            <xsl:value-of select="string (ns0:erpSystemId )"/>
          </tns:erpSystemId>
          <tns:action>
            <xsl:value-of select="ns0:action"/>
          </tns:action>
          <tns:created>
            <xsl:value-of select="ns0:created"/>
          </tns:created>
          <tns:updated>
            <xsl:value-of select="ns0:updated"/>
          </tns:updated>
        </tns:settled_Transactions_Output>
      </xsl:for-each>
    </tns:Settled_Transactions_OutputCollection>
  </xsl:template>
</xsl:stylesheet>
