<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SD_PaymentPanel_App/SD_GetPaymentsDetails/GetPaymentsDetailsBS" name="GetPaymentsDetailsBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="GetPaymentsDetailsBS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SD_PaymentPanel_App/SD_GetPaymentsDetails/GetPaymentsDetailsBS"/>
    <wsdl:binding name="GetPaymentsDetailsBS_ptt-binding" type="get:GetPaymentsDetailsBS_ptt" xmlns:get="http://xmlns.oracle.com/pcbpel/adapter/db/SD_PaymentPanel_App/SD_GetPaymentsDetails/GetPaymentsDetailsBS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="GetPaymentsDetailsBS">
            <soap:operation soapAction="GetPaymentsDetailsBS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>